// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using StockAndFlow.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StockAndFlow.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class InventoryItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "StockAndFlow.Models.InventoryItem",
                typeof(InventoryItem),
                baseEntityType,
                propertyCount: 19,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(InventoryItem).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var category = runtimeEntityType.AddProperty(
                "Category",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("Category", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Category>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var costPerUnit = runtimeEntityType.AddProperty(
                "CostPerUnit",
                typeof(decimal),
                propertyInfo: typeof(InventoryItem).GetProperty("CostPerUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<CostPerUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            costPerUnit.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var createdDate = runtimeEntityType.AddProperty(
                "CreatedDate",
                typeof(DateTime),
                propertyInfo: typeof(InventoryItem).GetProperty("CreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<CreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var deletedDate = runtimeEntityType.AddProperty(
                "DeletedDate",
                typeof(DateTime?),
                propertyInfo: typeof(InventoryItem).GetProperty("DeletedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<DeletedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var imagePath = runtimeEntityType.AddProperty(
                "ImagePath",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("ImagePath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<ImagePath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var isDeleted = runtimeEntityType.AddProperty(
                "IsDeleted",
                typeof(bool),
                propertyInfo: typeof(InventoryItem).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: false);
            isDeleted.AddAnnotation("Relational:DefaultValue", false);

            var lastModifiedDate = runtimeEntityType.AddProperty(
                "LastModifiedDate",
                typeof(DateTime),
                propertyInfo: typeof(InventoryItem).GetProperty("LastModifiedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<LastModifiedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var lastSyncedAt = runtimeEntityType.AddProperty(
                "LastSyncedAt",
                typeof(DateTime?),
                propertyInfo: typeof(InventoryItem).GetProperty("LastSyncedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<LastSyncedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var minimumStockLevel = runtimeEntityType.AddProperty(
                "MinimumStockLevel",
                typeof(decimal),
                propertyInfo: typeof(InventoryItem).GetProperty("MinimumStockLevel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<MinimumStockLevel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            minimumStockLevel.AddAnnotation("Relational:ColumnType", "decimal(18,3)");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var quantityOnHand = runtimeEntityType.AddProperty(
                "QuantityOnHand",
                typeof(decimal),
                propertyInfo: typeof(InventoryItem).GetProperty("QuantityOnHand", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<QuantityOnHand>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            quantityOnHand.AddAnnotation("Relational:ColumnType", "decimal(18,3)");

            var salePrice = runtimeEntityType.AddProperty(
                "SalePrice",
                typeof(decimal),
                propertyInfo: typeof(InventoryItem).GetProperty("SalePrice", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<SalePrice>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            salePrice.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var shopifyProductId = runtimeEntityType.AddProperty(
                "ShopifyProductId",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("ShopifyProductId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<ShopifyProductId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var shopifyVariantId = runtimeEntityType.AddProperty(
                "ShopifyVariantId",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("ShopifyVariantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<ShopifyVariantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var sku = runtimeEntityType.AddProperty(
                "Sku",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("Sku", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Sku>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);

            var supplier = runtimeEntityType.AddProperty(
                "Supplier",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("Supplier", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<Supplier>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var unitOfMeasure = runtimeEntityType.AddProperty(
                "UnitOfMeasure",
                typeof(string),
                propertyInfo: typeof(InventoryItem).GetProperty("UnitOfMeasure", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryItem).GetField("<UnitOfMeasure>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            unitOfMeasure.AddAnnotation("Relational:DefaultValue", "each");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { category });

            var index0 = runtimeEntityType.AddIndex(
                new[] { isDeleted });

            var index1 = runtimeEntityType.AddIndex(
                new[] { name });

            var index2 = runtimeEntityType.AddIndex(
                new[] { shopifyProductId });

            var index3 = runtimeEntityType.AddIndex(
                new[] { sku });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "InventoryItems");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
