// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using StockAndFlow.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StockAndFlow.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class InventoryAdjustmentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "StockAndFlow.Models.InventoryAdjustment",
                typeof(InventoryAdjustment),
                baseEntityType,
                propertyCount: 10,
                foreignKeyCount: 1,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var adjustmentDate = runtimeEntityType.AddProperty(
                "AdjustmentDate",
                typeof(DateTime),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("AdjustmentDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<AdjustmentDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var costPerUnit = runtimeEntityType.AddProperty(
                "CostPerUnit",
                typeof(decimal),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("CostPerUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<CostPerUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            costPerUnit.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var createdDate = runtimeEntityType.AddProperty(
                "CreatedDate",
                typeof(DateTime),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("CreatedDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<CreatedDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var inventoryItemId = runtimeEntityType.AddProperty(
                "InventoryItemId",
                typeof(Guid),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("InventoryItemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<InventoryItemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var inventoryItemName = runtimeEntityType.AddProperty(
                "InventoryItemName",
                typeof(string),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("InventoryItemName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<InventoryItemName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var quantityChange = runtimeEntityType.AddProperty(
                "QuantityChange",
                typeof(decimal),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("QuantityChange", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<QuantityChange>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            quantityChange.AddAnnotation("Relational:ColumnType", "decimal(18,3)");

            var reason = runtimeEntityType.AddProperty(
                "Reason",
                typeof(AdjustmentReason),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("Reason", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<Reason>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                providerPropertyType: typeof(string));
            reason.SetSentinelFromProviderValue("Damaged");

            var salePricePerUnit = runtimeEntityType.AddProperty(
                "SalePricePerUnit",
                typeof(decimal),
                propertyInfo: typeof(InventoryAdjustment).GetProperty("SalePricePerUnit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InventoryAdjustment).GetField("<SalePricePerUnit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            salePricePerUnit.AddAnnotation("Relational:ColumnType", "decimal(18,2)");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { adjustmentDate });
            index.AddAnnotation("Relational:Name", "IX_InventoryAdjustments_AdjustmentDate");

            var index0 = runtimeEntityType.AddIndex(
                new[] { inventoryItemId });
            index0.AddAnnotation("Relational:Name", "IX_InventoryAdjustments_InventoryItemId");

            var index1 = runtimeEntityType.AddIndex(
                new[] { reason });
            index1.AddAnnotation("Relational:Name", "IX_InventoryAdjustments_Reason");

            var index2 = runtimeEntityType.AddIndex(
                new[] { inventoryItemId, adjustmentDate });
            index2.AddAnnotation("Relational:Name", "IX_InventoryAdjustments_InventoryItemId_AdjustmentDate");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("InventoryItemId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "InventoryAdjustments");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
