// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StockAndFlow.Data.CompiledModels
{
    public partial class StockAndFlowDbContextModel
    {
        private StockAndFlowDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e7c69dda-9ca5-4fe4-b183-58eb652739ca"), entityTypeCount: 6)
        {
        }

        partial void Initialize()
        {
            var businessSettings = BusinessSettingsEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var expense = ExpenseEntityType.Create(this);
            var inventoryAdjustment = InventoryAdjustmentEntityType.Create(this);
            var inventoryItem = InventoryItemEntityType.Create(this);
            var sale = SaleEntityType.Create(this);

            ExpenseEntityType.CreateForeignKey1(expense, inventoryItem);
            InventoryAdjustmentEntityType.CreateForeignKey1(inventoryAdjustment, inventoryItem);
            SaleEntityType.CreateForeignKey1(sale, customer);
            SaleEntityType.CreateForeignKey2(sale, inventoryItem);

            BusinessSettingsEntityType.CreateAnnotations(businessSettings);
            CustomerEntityType.CreateAnnotations(customer);
            ExpenseEntityType.CreateAnnotations(expense);
            InventoryAdjustmentEntityType.CreateAnnotations(inventoryAdjustment);
            InventoryItemEntityType.CreateAnnotations(inventoryItem);
            SaleEntityType.CreateAnnotations(sale);

            AddAnnotation("ProductVersion", "10.0.10");
        }
    }
}
