// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using StockAndFlow.Data;
using StockAndFlow.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(StockAndFlowDbContext), typeof(StockAndFlowDbContextModel))]
