// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StockAndFlow.Data.CompiledModels
{
    public partial class StockAndFlowDbContextModel
    {
        partial void Initialize()
        {
            var businessSettings = BusinessSettingsEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var expense = ExpenseEntityType.Create(this);
            var inventoryAdjustment = InventoryAdjustmentEntityType.Create(this);
            var inventoryItem = InventoryItemEntityType.Create(this);
            var sale = SaleEntityType.Create(this);

            ExpenseEntityType.CreateForeignKey1(expense, inventoryItem);
            InventoryAdjustmentEntityType.CreateForeignKey1(inventoryAdjustment, inventoryItem);
            SaleEntityType.CreateForeignKey1(sale, customer);
            SaleEntityType.CreateForeignKey2(sale, inventoryItem);

            BusinessSettingsEntityType.CreateAnnotations(businessSettings);
            CustomerEntityType.CreateAnnotations(customer);
            ExpenseEntityType.CreateAnnotations(expense);
            InventoryAdjustmentEntityType.CreateAnnotations(inventoryAdjustment);
            InventoryItemEntityType.CreateAnnotations(inventoryItem);
            SaleEntityType.CreateAnnotations(sale);

            AddAnnotation("ProductVersion", "8.0.11");
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var businessSettings = FindEntityType("StockAndFlow.Models.BusinessSettings")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            businessSettings.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var stockAndFlowModelsBusinessSettingsTableBase = new TableBase("StockAndFlow.Models.BusinessSettings", null, relationalModel);
            var addressColumnBase = new ColumnBase<ColumnMappingBase>("Address", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("Address", addressColumnBase);
            var businessNameColumnBase = new ColumnBase<ColumnMappingBase>("BusinessName", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("BusinessName", businessNameColumnBase);
            var cityColumnBase = new ColumnBase<ColumnMappingBase>("City", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("City", cityColumnBase);
            var defaultTaxStateCodeColumnBase = new ColumnBase<ColumnMappingBase>("DefaultTaxStateCode", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("DefaultTaxStateCode", defaultTaxStateCodeColumnBase);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("Email", emailColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsBusinessSettingsTableBase);
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("Id", idColumnBase);
            var lastModifiedColumnBase = new ColumnBase<ColumnMappingBase>("LastModified", "TEXT", stockAndFlowModelsBusinessSettingsTableBase);
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("LastModified", lastModifiedColumnBase);
            var logoPathColumnBase = new ColumnBase<ColumnMappingBase>("LogoPath", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("LogoPath", logoPathColumnBase);
            var phoneColumnBase = new ColumnBase<ColumnMappingBase>("Phone", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("Phone", phoneColumnBase);
            var stateColumnBase = new ColumnBase<ColumnMappingBase>("State", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("State", stateColumnBase);
            var taxIdColumnBase = new ColumnBase<ColumnMappingBase>("TaxId", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("TaxId", taxIdColumnBase);
            var websiteColumnBase = new ColumnBase<ColumnMappingBase>("Website", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("Website", websiteColumnBase);
            var zipCodeColumnBase = new ColumnBase<ColumnMappingBase>("ZipCode", "TEXT", stockAndFlowModelsBusinessSettingsTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsBusinessSettingsTableBase.Columns.Add("ZipCode", zipCodeColumnBase);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.BusinessSettings", stockAndFlowModelsBusinessSettingsTableBase);
            var stockAndFlowModelsBusinessSettingsMappingBase = new TableMappingBase<ColumnMappingBase>(businessSettings, stockAndFlowModelsBusinessSettingsTableBase, true);
            stockAndFlowModelsBusinessSettingsTableBase.AddTypeMapping(stockAndFlowModelsBusinessSettingsMappingBase, false);
            defaultTableMappings.Add(stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, businessSettings.FindProperty("Id")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)addressColumnBase, businessSettings.FindProperty("Address")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)businessNameColumnBase, businessSettings.FindProperty("BusinessName")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cityColumnBase, businessSettings.FindProperty("City")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)defaultTaxStateCodeColumnBase, businessSettings.FindProperty("DefaultTaxStateCode")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, businessSettings.FindProperty("Email")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastModifiedColumnBase, businessSettings.FindProperty("LastModified")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)logoPathColumnBase, businessSettings.FindProperty("LogoPath")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneColumnBase, businessSettings.FindProperty("Phone")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)stateColumnBase, businessSettings.FindProperty("State")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)taxIdColumnBase, businessSettings.FindProperty("TaxId")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)websiteColumnBase, businessSettings.FindProperty("Website")!, stockAndFlowModelsBusinessSettingsMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)zipCodeColumnBase, businessSettings.FindProperty("ZipCode")!, stockAndFlowModelsBusinessSettingsMappingBase);

            var tableMappings = new List<TableMapping>();
            businessSettings.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var businessSettingsTable = new Table("BusinessSettings", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", businessSettingsTable);
            businessSettingsTable.Columns.Add("Id", idColumn);
            var addressColumn = new Column("Address", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("Address", addressColumn);
            var businessNameColumn = new Column("BusinessName", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("BusinessName", businessNameColumn);
            var cityColumn = new Column("City", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("City", cityColumn);
            var defaultTaxStateCodeColumn = new Column("DefaultTaxStateCode", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("DefaultTaxStateCode", defaultTaxStateCodeColumn);
            var emailColumn = new Column("Email", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("Email", emailColumn);
            var lastModifiedColumn = new Column("LastModified", "TEXT", businessSettingsTable);
            businessSettingsTable.Columns.Add("LastModified", lastModifiedColumn);
            var logoPathColumn = new Column("LogoPath", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("LogoPath", logoPathColumn);
            var phoneColumn = new Column("Phone", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("Phone", phoneColumn);
            var stateColumn = new Column("State", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("State", stateColumn);
            var taxIdColumn = new Column("TaxId", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("TaxId", taxIdColumn);
            var websiteColumn = new Column("Website", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("Website", websiteColumn);
            var zipCodeColumn = new Column("ZipCode", "TEXT", businessSettingsTable)
            {
                IsNullable = true
            };
            businessSettingsTable.Columns.Add("ZipCode", zipCodeColumn);
            var pK_BusinessSettings = new UniqueConstraint("PK_BusinessSettings", businessSettingsTable, new[] { idColumn });
            businessSettingsTable.PrimaryKey = pK_BusinessSettings;
            var pK_BusinessSettingsUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.BusinessSettings",
                new[] { "Id" });
            pK_BusinessSettings.MappedKeys.Add(pK_BusinessSettingsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_BusinessSettingsUc).Add(pK_BusinessSettings);
            businessSettingsTable.UniqueConstraints.Add("PK_BusinessSettings", pK_BusinessSettings);
            relationalModel.Tables.Add(("BusinessSettings", null), businessSettingsTable);
            var businessSettingsTableMapping = new TableMapping(businessSettings, businessSettingsTable, true);
            businessSettingsTable.AddTypeMapping(businessSettingsTableMapping, false);
            tableMappings.Add(businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, businessSettings.FindProperty("Id")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(addressColumn, businessSettings.FindProperty("Address")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(businessNameColumn, businessSettings.FindProperty("BusinessName")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(cityColumn, businessSettings.FindProperty("City")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(defaultTaxStateCodeColumn, businessSettings.FindProperty("DefaultTaxStateCode")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, businessSettings.FindProperty("Email")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(lastModifiedColumn, businessSettings.FindProperty("LastModified")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(logoPathColumn, businessSettings.FindProperty("LogoPath")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(phoneColumn, businessSettings.FindProperty("Phone")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(stateColumn, businessSettings.FindProperty("State")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(taxIdColumn, businessSettings.FindProperty("TaxId")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(websiteColumn, businessSettings.FindProperty("Website")!, businessSettingsTableMapping);
            RelationalModel.CreateColumnMapping(zipCodeColumn, businessSettings.FindProperty("ZipCode")!, businessSettingsTableMapping);

            var customer = FindEntityType("StockAndFlow.Models.Customer")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            customer.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var stockAndFlowModelsCustomerTableBase = new TableBase("StockAndFlow.Models.Customer", null, relationalModel);
            var addressColumnBase0 = new ColumnBase<ColumnMappingBase>("Address", "TEXT", stockAndFlowModelsCustomerTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsCustomerTableBase.Columns.Add("Address", addressColumnBase0);
            var createdDateColumnBase = new ColumnBase<ColumnMappingBase>("CreatedDate", "TEXT", stockAndFlowModelsCustomerTableBase);
            stockAndFlowModelsCustomerTableBase.Columns.Add("CreatedDate", createdDateColumnBase);
            var deletedDateColumnBase = new ColumnBase<ColumnMappingBase>("DeletedDate", "TEXT", stockAndFlowModelsCustomerTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsCustomerTableBase.Columns.Add("DeletedDate", deletedDateColumnBase);
            var emailColumnBase0 = new ColumnBase<ColumnMappingBase>("Email", "TEXT", stockAndFlowModelsCustomerTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsCustomerTableBase.Columns.Add("Email", emailColumnBase0);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsCustomerTableBase);
            stockAndFlowModelsCustomerTableBase.Columns.Add("Id", idColumnBase0);
            var isDeletedColumnBase = new ColumnBase<ColumnMappingBase>("IsDeleted", "INTEGER", stockAndFlowModelsCustomerTableBase);
            stockAndFlowModelsCustomerTableBase.Columns.Add("IsDeleted", isDeletedColumnBase);
            var lastModifiedDateColumnBase = new ColumnBase<ColumnMappingBase>("LastModifiedDate", "TEXT", stockAndFlowModelsCustomerTableBase);
            stockAndFlowModelsCustomerTableBase.Columns.Add("LastModifiedDate", lastModifiedDateColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", stockAndFlowModelsCustomerTableBase);
            stockAndFlowModelsCustomerTableBase.Columns.Add("Name", nameColumnBase);
            var notesColumnBase = new ColumnBase<ColumnMappingBase>("Notes", "TEXT", stockAndFlowModelsCustomerTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsCustomerTableBase.Columns.Add("Notes", notesColumnBase);
            var phoneColumnBase0 = new ColumnBase<ColumnMappingBase>("Phone", "TEXT", stockAndFlowModelsCustomerTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsCustomerTableBase.Columns.Add("Phone", phoneColumnBase0);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.Customer", stockAndFlowModelsCustomerTableBase);
            var stockAndFlowModelsCustomerMappingBase = new TableMappingBase<ColumnMappingBase>(customer, stockAndFlowModelsCustomerTableBase, true);
            stockAndFlowModelsCustomerTableBase.AddTypeMapping(stockAndFlowModelsCustomerMappingBase, false);
            defaultTableMappings0.Add(stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, customer.FindProperty("Id")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)addressColumnBase0, customer.FindProperty("Address")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdDateColumnBase, customer.FindProperty("CreatedDate")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)deletedDateColumnBase, customer.FindProperty("DeletedDate")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase0, customer.FindProperty("Email")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isDeletedColumnBase, customer.FindProperty("IsDeleted")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastModifiedDateColumnBase, customer.FindProperty("LastModifiedDate")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, customer.FindProperty("Name")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)notesColumnBase, customer.FindProperty("Notes")!, stockAndFlowModelsCustomerMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneColumnBase0, customer.FindProperty("Phone")!, stockAndFlowModelsCustomerMappingBase);

            var tableMappings0 = new List<TableMapping>();
            customer.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var customersTable = new Table("Customers", null, relationalModel);
            var idColumn0 = new Column("Id", "TEXT", customersTable);
            customersTable.Columns.Add("Id", idColumn0);
            var addressColumn0 = new Column("Address", "TEXT", customersTable)
            {
                IsNullable = true
            };
            customersTable.Columns.Add("Address", addressColumn0);
            var createdDateColumn = new Column("CreatedDate", "TEXT", customersTable);
            customersTable.Columns.Add("CreatedDate", createdDateColumn);
            var deletedDateColumn = new Column("DeletedDate", "TEXT", customersTable)
            {
                IsNullable = true
            };
            customersTable.Columns.Add("DeletedDate", deletedDateColumn);
            var emailColumn0 = new Column("Email", "TEXT", customersTable)
            {
                IsNullable = true
            };
            customersTable.Columns.Add("Email", emailColumn0);
            var isDeletedColumn = new Column("IsDeleted", "INTEGER", customersTable);
            customersTable.Columns.Add("IsDeleted", isDeletedColumn);
            var lastModifiedDateColumn = new Column("LastModifiedDate", "TEXT", customersTable);
            customersTable.Columns.Add("LastModifiedDate", lastModifiedDateColumn);
            var nameColumn = new Column("Name", "TEXT", customersTable);
            customersTable.Columns.Add("Name", nameColumn);
            var notesColumn = new Column("Notes", "TEXT", customersTable)
            {
                IsNullable = true
            };
            customersTable.Columns.Add("Notes", notesColumn);
            var phoneColumn0 = new Column("Phone", "TEXT", customersTable)
            {
                IsNullable = true
            };
            customersTable.Columns.Add("Phone", phoneColumn0);
            var pK_Customers = new UniqueConstraint("PK_Customers", customersTable, new[] { idColumn0 });
            customersTable.PrimaryKey = pK_Customers;
            var pK_CustomersUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.Customer",
                new[] { "Id" });
            pK_Customers.MappedKeys.Add(pK_CustomersUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_CustomersUc).Add(pK_Customers);
            customersTable.UniqueConstraints.Add("PK_Customers", pK_Customers);
            var iX_Customers_Email = new TableIndex(
            "IX_Customers_Email", customersTable, new[] { emailColumn0 }, false);
            var iX_Customers_EmailIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Customer",
                new[] { "Email" });
            iX_Customers_Email.MappedIndexes.Add(iX_Customers_EmailIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Customers_EmailIx).Add(iX_Customers_Email);
            customersTable.Indexes.Add("IX_Customers_Email", iX_Customers_Email);
            var iX_Customers_Name = new TableIndex(
            "IX_Customers_Name", customersTable, new[] { nameColumn }, false);
            var iX_Customers_NameIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Customer",
                new[] { "Name" });
            iX_Customers_Name.MappedIndexes.Add(iX_Customers_NameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Customers_NameIx).Add(iX_Customers_Name);
            customersTable.Indexes.Add("IX_Customers_Name", iX_Customers_Name);
            relationalModel.Tables.Add(("Customers", null), customersTable);
            var customersTableMapping = new TableMapping(customer, customersTable, true);
            customersTable.AddTypeMapping(customersTableMapping, false);
            tableMappings0.Add(customersTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, customer.FindProperty("Id")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(addressColumn0, customer.FindProperty("Address")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(createdDateColumn, customer.FindProperty("CreatedDate")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(deletedDateColumn, customer.FindProperty("DeletedDate")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn0, customer.FindProperty("Email")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(isDeletedColumn, customer.FindProperty("IsDeleted")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(lastModifiedDateColumn, customer.FindProperty("LastModifiedDate")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, customer.FindProperty("Name")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(notesColumn, customer.FindProperty("Notes")!, customersTableMapping);
            RelationalModel.CreateColumnMapping(phoneColumn0, customer.FindProperty("Phone")!, customersTableMapping);

            var expense = FindEntityType("StockAndFlow.Models.Expense")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            expense.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var stockAndFlowModelsExpenseTableBase = new TableBase("StockAndFlow.Models.Expense", null, relationalModel);
            var amountColumnBase = new ColumnBase<ColumnMappingBase>("Amount", "decimal(18,2)", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("Amount", amountColumnBase);
            var categoryColumnBase = new ColumnBase<ColumnMappingBase>("Category", "TEXT", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("Category", categoryColumnBase);
            var createdDateColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedDate", "TEXT", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("CreatedDate", createdDateColumnBase0);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", stockAndFlowModelsExpenseTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsExpenseTableBase.Columns.Add("Description", descriptionColumnBase);
            var expenseDateColumnBase = new ColumnBase<ColumnMappingBase>("ExpenseDate", "TEXT", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("ExpenseDate", expenseDateColumnBase);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("Id", idColumnBase1);
            var inventoryItemIdColumnBase = new ColumnBase<ColumnMappingBase>("InventoryItemId", "TEXT", stockAndFlowModelsExpenseTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsExpenseTableBase.Columns.Add("InventoryItemId", inventoryItemIdColumnBase);
            var linkedItemNameColumnBase = new ColumnBase<ColumnMappingBase>("LinkedItemName", "TEXT", stockAndFlowModelsExpenseTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsExpenseTableBase.Columns.Add("LinkedItemName", linkedItemNameColumnBase);
            var receiptImagePathColumnBase = new ColumnBase<ColumnMappingBase>("ReceiptImagePath", "TEXT", stockAndFlowModelsExpenseTableBase);
            stockAndFlowModelsExpenseTableBase.Columns.Add("ReceiptImagePath", receiptImagePathColumnBase);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.Expense", stockAndFlowModelsExpenseTableBase);
            var stockAndFlowModelsExpenseMappingBase = new TableMappingBase<ColumnMappingBase>(expense, stockAndFlowModelsExpenseTableBase, true);
            stockAndFlowModelsExpenseTableBase.AddTypeMapping(stockAndFlowModelsExpenseMappingBase, false);
            defaultTableMappings1.Add(stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, expense.FindProperty("Id")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)amountColumnBase, expense.FindProperty("Amount")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)categoryColumnBase, expense.FindProperty("Category")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdDateColumnBase0, expense.FindProperty("CreatedDate")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, expense.FindProperty("Description")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expenseDateColumnBase, expense.FindProperty("ExpenseDate")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inventoryItemIdColumnBase, expense.FindProperty("InventoryItemId")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)linkedItemNameColumnBase, expense.FindProperty("LinkedItemName")!, stockAndFlowModelsExpenseMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)receiptImagePathColumnBase, expense.FindProperty("ReceiptImagePath")!, stockAndFlowModelsExpenseMappingBase);

            var tableMappings1 = new List<TableMapping>();
            expense.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var expensesTable = new Table("Expenses", null, relationalModel);
            var idColumn1 = new Column("Id", "TEXT", expensesTable);
            expensesTable.Columns.Add("Id", idColumn1);
            var amountColumn = new Column("Amount", "decimal(18,2)", expensesTable);
            expensesTable.Columns.Add("Amount", amountColumn);
            var categoryColumn = new Column("Category", "TEXT", expensesTable);
            expensesTable.Columns.Add("Category", categoryColumn);
            var createdDateColumn0 = new Column("CreatedDate", "TEXT", expensesTable);
            expensesTable.Columns.Add("CreatedDate", createdDateColumn0);
            var descriptionColumn = new Column("Description", "TEXT", expensesTable)
            {
                IsNullable = true
            };
            expensesTable.Columns.Add("Description", descriptionColumn);
            var expenseDateColumn = new Column("ExpenseDate", "TEXT", expensesTable);
            expensesTable.Columns.Add("ExpenseDate", expenseDateColumn);
            var inventoryItemIdColumn = new Column("InventoryItemId", "TEXT", expensesTable)
            {
                IsNullable = true
            };
            expensesTable.Columns.Add("InventoryItemId", inventoryItemIdColumn);
            var linkedItemNameColumn = new Column("LinkedItemName", "TEXT", expensesTable)
            {
                IsNullable = true
            };
            expensesTable.Columns.Add("LinkedItemName", linkedItemNameColumn);
            var receiptImagePathColumn = new Column("ReceiptImagePath", "TEXT", expensesTable);
            expensesTable.Columns.Add("ReceiptImagePath", receiptImagePathColumn);
            var pK_Expenses = new UniqueConstraint("PK_Expenses", expensesTable, new[] { idColumn1 });
            expensesTable.PrimaryKey = pK_Expenses;
            var pK_ExpensesUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.Expense",
                new[] { "Id" });
            pK_Expenses.MappedKeys.Add(pK_ExpensesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ExpensesUc).Add(pK_Expenses);
            expensesTable.UniqueConstraints.Add("PK_Expenses", pK_Expenses);
            var iX_Expenses_Category = new TableIndex(
            "IX_Expenses_Category", expensesTable, new[] { categoryColumn }, false);
            var iX_Expenses_CategoryIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Expense",
                new[] { "Category" });
            iX_Expenses_Category.MappedIndexes.Add(iX_Expenses_CategoryIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Expenses_CategoryIx).Add(iX_Expenses_Category);
            expensesTable.Indexes.Add("IX_Expenses_Category", iX_Expenses_Category);
            var iX_Expenses_Category_ExpenseDate = new TableIndex(
            "IX_Expenses_Category_ExpenseDate", expensesTable, new[] { categoryColumn, expenseDateColumn }, false);
            var iX_Expenses_Category_ExpenseDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Expense",
                new[] { "Category", "ExpenseDate" });
            iX_Expenses_Category_ExpenseDate.MappedIndexes.Add(iX_Expenses_Category_ExpenseDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Expenses_Category_ExpenseDateIx).Add(iX_Expenses_Category_ExpenseDate);
            expensesTable.Indexes.Add("IX_Expenses_Category_ExpenseDate", iX_Expenses_Category_ExpenseDate);
            var iX_Expenses_ExpenseDate = new TableIndex(
            "IX_Expenses_ExpenseDate", expensesTable, new[] { expenseDateColumn }, false);
            var iX_Expenses_ExpenseDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Expense",
                new[] { "ExpenseDate" });
            iX_Expenses_ExpenseDate.MappedIndexes.Add(iX_Expenses_ExpenseDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Expenses_ExpenseDateIx).Add(iX_Expenses_ExpenseDate);
            expensesTable.Indexes.Add("IX_Expenses_ExpenseDate", iX_Expenses_ExpenseDate);
            var iX_Expenses_InventoryItemId = new TableIndex(
            "IX_Expenses_InventoryItemId", expensesTable, new[] { inventoryItemIdColumn }, false);
            var iX_Expenses_InventoryItemIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Expense",
                new[] { "InventoryItemId" });
            iX_Expenses_InventoryItemId.MappedIndexes.Add(iX_Expenses_InventoryItemIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Expenses_InventoryItemIdIx).Add(iX_Expenses_InventoryItemId);
            expensesTable.Indexes.Add("IX_Expenses_InventoryItemId", iX_Expenses_InventoryItemId);
            relationalModel.Tables.Add(("Expenses", null), expensesTable);
            var expensesTableMapping = new TableMapping(expense, expensesTable, true);
            expensesTable.AddTypeMapping(expensesTableMapping, false);
            tableMappings1.Add(expensesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, expense.FindProperty("Id")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(amountColumn, expense.FindProperty("Amount")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(categoryColumn, expense.FindProperty("Category")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(createdDateColumn0, expense.FindProperty("CreatedDate")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, expense.FindProperty("Description")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(expenseDateColumn, expense.FindProperty("ExpenseDate")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(inventoryItemIdColumn, expense.FindProperty("InventoryItemId")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(linkedItemNameColumn, expense.FindProperty("LinkedItemName")!, expensesTableMapping);
            RelationalModel.CreateColumnMapping(receiptImagePathColumn, expense.FindProperty("ReceiptImagePath")!, expensesTableMapping);

            var inventoryAdjustment = FindEntityType("StockAndFlow.Models.InventoryAdjustment")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            inventoryAdjustment.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var stockAndFlowModelsInventoryAdjustmentTableBase = new TableBase("StockAndFlow.Models.InventoryAdjustment", null, relationalModel);
            var adjustmentDateColumnBase = new ColumnBase<ColumnMappingBase>("AdjustmentDate", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("AdjustmentDate", adjustmentDateColumnBase);
            var costPerUnitColumnBase = new ColumnBase<ColumnMappingBase>("CostPerUnit", "decimal(18,2)", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("CostPerUnit", costPerUnitColumnBase);
            var createdDateColumnBase1 = new ColumnBase<ColumnMappingBase>("CreatedDate", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("CreatedDate", createdDateColumnBase1);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("Id", idColumnBase2);
            var inventoryItemIdColumnBase0 = new ColumnBase<ColumnMappingBase>("InventoryItemId", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("InventoryItemId", inventoryItemIdColumnBase0);
            var inventoryItemNameColumnBase = new ColumnBase<ColumnMappingBase>("InventoryItemName", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("InventoryItemName", inventoryItemNameColumnBase);
            var notesColumnBase0 = new ColumnBase<ColumnMappingBase>("Notes", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("Notes", notesColumnBase0);
            var quantityChangeColumnBase = new ColumnBase<ColumnMappingBase>("QuantityChange", "INTEGER", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("QuantityChange", quantityChangeColumnBase);
            var reasonColumnBase = new ColumnBase<ColumnMappingBase>("Reason", "TEXT", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("Reason", reasonColumnBase);
            var salePricePerUnitColumnBase = new ColumnBase<ColumnMappingBase>("SalePricePerUnit", "decimal(18,2)", stockAndFlowModelsInventoryAdjustmentTableBase);
            stockAndFlowModelsInventoryAdjustmentTableBase.Columns.Add("SalePricePerUnit", salePricePerUnitColumnBase);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.InventoryAdjustment", stockAndFlowModelsInventoryAdjustmentTableBase);
            var stockAndFlowModelsInventoryAdjustmentMappingBase = new TableMappingBase<ColumnMappingBase>(inventoryAdjustment, stockAndFlowModelsInventoryAdjustmentTableBase, true);
            stockAndFlowModelsInventoryAdjustmentTableBase.AddTypeMapping(stockAndFlowModelsInventoryAdjustmentMappingBase, false);
            defaultTableMappings2.Add(stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, inventoryAdjustment.FindProperty("Id")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)adjustmentDateColumnBase, inventoryAdjustment.FindProperty("AdjustmentDate")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)costPerUnitColumnBase, inventoryAdjustment.FindProperty("CostPerUnit")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdDateColumnBase1, inventoryAdjustment.FindProperty("CreatedDate")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inventoryItemIdColumnBase0, inventoryAdjustment.FindProperty("InventoryItemId")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inventoryItemNameColumnBase, inventoryAdjustment.FindProperty("InventoryItemName")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)notesColumnBase0, inventoryAdjustment.FindProperty("Notes")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityChangeColumnBase, inventoryAdjustment.FindProperty("QuantityChange")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)reasonColumnBase, inventoryAdjustment.FindProperty("Reason")!, stockAndFlowModelsInventoryAdjustmentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)salePricePerUnitColumnBase, inventoryAdjustment.FindProperty("SalePricePerUnit")!, stockAndFlowModelsInventoryAdjustmentMappingBase);

            var tableMappings2 = new List<TableMapping>();
            inventoryAdjustment.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var inventoryAdjustmentsTable = new Table("InventoryAdjustments", null, relationalModel);
            var idColumn2 = new Column("Id", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("Id", idColumn2);
            var adjustmentDateColumn = new Column("AdjustmentDate", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("AdjustmentDate", adjustmentDateColumn);
            var costPerUnitColumn = new Column("CostPerUnit", "decimal(18,2)", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("CostPerUnit", costPerUnitColumn);
            var createdDateColumn1 = new Column("CreatedDate", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("CreatedDate", createdDateColumn1);
            var inventoryItemIdColumn0 = new Column("InventoryItemId", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("InventoryItemId", inventoryItemIdColumn0);
            var inventoryItemNameColumn = new Column("InventoryItemName", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("InventoryItemName", inventoryItemNameColumn);
            var notesColumn0 = new Column("Notes", "TEXT", inventoryAdjustmentsTable)
            {
                IsNullable = true
            };
            inventoryAdjustmentsTable.Columns.Add("Notes", notesColumn0);
            var quantityChangeColumn = new Column("QuantityChange", "INTEGER", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("QuantityChange", quantityChangeColumn);
            var reasonColumn = new Column("Reason", "TEXT", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("Reason", reasonColumn);
            var salePricePerUnitColumn = new Column("SalePricePerUnit", "decimal(18,2)", inventoryAdjustmentsTable);
            inventoryAdjustmentsTable.Columns.Add("SalePricePerUnit", salePricePerUnitColumn);
            var pK_InventoryAdjustments = new UniqueConstraint("PK_InventoryAdjustments", inventoryAdjustmentsTable, new[] { idColumn2 });
            inventoryAdjustmentsTable.PrimaryKey = pK_InventoryAdjustments;
            var pK_InventoryAdjustmentsUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "Id" });
            pK_InventoryAdjustments.MappedKeys.Add(pK_InventoryAdjustmentsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_InventoryAdjustmentsUc).Add(pK_InventoryAdjustments);
            inventoryAdjustmentsTable.UniqueConstraints.Add("PK_InventoryAdjustments", pK_InventoryAdjustments);
            var iX_InventoryAdjustments_AdjustmentDate = new TableIndex(
            "IX_InventoryAdjustments_AdjustmentDate", inventoryAdjustmentsTable, new[] { adjustmentDateColumn }, false);
            var iX_InventoryAdjustments_AdjustmentDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "AdjustmentDate" });
            iX_InventoryAdjustments_AdjustmentDate.MappedIndexes.Add(iX_InventoryAdjustments_AdjustmentDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryAdjustments_AdjustmentDateIx).Add(iX_InventoryAdjustments_AdjustmentDate);
            inventoryAdjustmentsTable.Indexes.Add("IX_InventoryAdjustments_AdjustmentDate", iX_InventoryAdjustments_AdjustmentDate);
            var iX_InventoryAdjustments_InventoryItemId = new TableIndex(
            "IX_InventoryAdjustments_InventoryItemId", inventoryAdjustmentsTable, new[] { inventoryItemIdColumn0 }, false);
            var iX_InventoryAdjustments_InventoryItemIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "InventoryItemId" });
            iX_InventoryAdjustments_InventoryItemId.MappedIndexes.Add(iX_InventoryAdjustments_InventoryItemIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryAdjustments_InventoryItemIdIx).Add(iX_InventoryAdjustments_InventoryItemId);
            inventoryAdjustmentsTable.Indexes.Add("IX_InventoryAdjustments_InventoryItemId", iX_InventoryAdjustments_InventoryItemId);
            var iX_InventoryAdjustments_InventoryItemId_AdjustmentDate = new TableIndex(
            "IX_InventoryAdjustments_InventoryItemId_AdjustmentDate", inventoryAdjustmentsTable, new[] { inventoryItemIdColumn0, adjustmentDateColumn }, false);
            var iX_InventoryAdjustments_InventoryItemId_AdjustmentDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "InventoryItemId", "AdjustmentDate" });
            iX_InventoryAdjustments_InventoryItemId_AdjustmentDate.MappedIndexes.Add(iX_InventoryAdjustments_InventoryItemId_AdjustmentDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryAdjustments_InventoryItemId_AdjustmentDateIx).Add(iX_InventoryAdjustments_InventoryItemId_AdjustmentDate);
            inventoryAdjustmentsTable.Indexes.Add("IX_InventoryAdjustments_InventoryItemId_AdjustmentDate", iX_InventoryAdjustments_InventoryItemId_AdjustmentDate);
            var iX_InventoryAdjustments_Reason = new TableIndex(
            "IX_InventoryAdjustments_Reason", inventoryAdjustmentsTable, new[] { reasonColumn }, false);
            var iX_InventoryAdjustments_ReasonIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "Reason" });
            iX_InventoryAdjustments_Reason.MappedIndexes.Add(iX_InventoryAdjustments_ReasonIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryAdjustments_ReasonIx).Add(iX_InventoryAdjustments_Reason);
            inventoryAdjustmentsTable.Indexes.Add("IX_InventoryAdjustments_Reason", iX_InventoryAdjustments_Reason);
            relationalModel.Tables.Add(("InventoryAdjustments", null), inventoryAdjustmentsTable);
            var inventoryAdjustmentsTableMapping = new TableMapping(inventoryAdjustment, inventoryAdjustmentsTable, true);
            inventoryAdjustmentsTable.AddTypeMapping(inventoryAdjustmentsTableMapping, false);
            tableMappings2.Add(inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, inventoryAdjustment.FindProperty("Id")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(adjustmentDateColumn, inventoryAdjustment.FindProperty("AdjustmentDate")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(costPerUnitColumn, inventoryAdjustment.FindProperty("CostPerUnit")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(createdDateColumn1, inventoryAdjustment.FindProperty("CreatedDate")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(inventoryItemIdColumn0, inventoryAdjustment.FindProperty("InventoryItemId")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(inventoryItemNameColumn, inventoryAdjustment.FindProperty("InventoryItemName")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(notesColumn0, inventoryAdjustment.FindProperty("Notes")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(quantityChangeColumn, inventoryAdjustment.FindProperty("QuantityChange")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(reasonColumn, inventoryAdjustment.FindProperty("Reason")!, inventoryAdjustmentsTableMapping);
            RelationalModel.CreateColumnMapping(salePricePerUnitColumn, inventoryAdjustment.FindProperty("SalePricePerUnit")!, inventoryAdjustmentsTableMapping);

            var inventoryItem = FindEntityType("StockAndFlow.Models.InventoryItem")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            inventoryItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var stockAndFlowModelsInventoryItemTableBase = new TableBase("StockAndFlow.Models.InventoryItem", null, relationalModel);
            var categoryColumnBase0 = new ColumnBase<ColumnMappingBase>("Category", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Category", categoryColumnBase0);
            var costPerUnitColumnBase0 = new ColumnBase<ColumnMappingBase>("CostPerUnit", "decimal(18,2)", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("CostPerUnit", costPerUnitColumnBase0);
            var createdDateColumnBase2 = new ColumnBase<ColumnMappingBase>("CreatedDate", "TEXT", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("CreatedDate", createdDateColumnBase2);
            var deletedDateColumnBase0 = new ColumnBase<ColumnMappingBase>("DeletedDate", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("DeletedDate", deletedDateColumnBase0);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Id", idColumnBase3);
            var imagePathColumnBase = new ColumnBase<ColumnMappingBase>("ImagePath", "TEXT", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("ImagePath", imagePathColumnBase);
            var isDeletedColumnBase0 = new ColumnBase<ColumnMappingBase>("IsDeleted", "INTEGER", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("IsDeleted", isDeletedColumnBase0);
            var lastModifiedDateColumnBase0 = new ColumnBase<ColumnMappingBase>("LastModifiedDate", "TEXT", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("LastModifiedDate", lastModifiedDateColumnBase0);
            var lastSyncedAtColumnBase = new ColumnBase<ColumnMappingBase>("LastSyncedAt", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("LastSyncedAt", lastSyncedAtColumnBase);
            var minimumStockLevelColumnBase = new ColumnBase<ColumnMappingBase>("MinimumStockLevel", "INTEGER", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("MinimumStockLevel", minimumStockLevelColumnBase);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Name", nameColumnBase0);
            var notesColumnBase1 = new ColumnBase<ColumnMappingBase>("Notes", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Notes", notesColumnBase1);
            var quantityOnHandColumnBase = new ColumnBase<ColumnMappingBase>("QuantityOnHand", "INTEGER", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("QuantityOnHand", quantityOnHandColumnBase);
            var salePriceColumnBase = new ColumnBase<ColumnMappingBase>("SalePrice", "decimal(18,2)", stockAndFlowModelsInventoryItemTableBase);
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("SalePrice", salePriceColumnBase);
            var shopifyProductIdColumnBase = new ColumnBase<ColumnMappingBase>("ShopifyProductId", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("ShopifyProductId", shopifyProductIdColumnBase);
            var shopifyVariantIdColumnBase = new ColumnBase<ColumnMappingBase>("ShopifyVariantId", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("ShopifyVariantId", shopifyVariantIdColumnBase);
            var skuColumnBase = new ColumnBase<ColumnMappingBase>("Sku", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Sku", skuColumnBase);
            var supplierColumnBase = new ColumnBase<ColumnMappingBase>("Supplier", "TEXT", stockAndFlowModelsInventoryItemTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsInventoryItemTableBase.Columns.Add("Supplier", supplierColumnBase);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.InventoryItem", stockAndFlowModelsInventoryItemTableBase);
            var stockAndFlowModelsInventoryItemMappingBase = new TableMappingBase<ColumnMappingBase>(inventoryItem, stockAndFlowModelsInventoryItemTableBase, true);
            stockAndFlowModelsInventoryItemTableBase.AddTypeMapping(stockAndFlowModelsInventoryItemMappingBase, false);
            defaultTableMappings3.Add(stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, inventoryItem.FindProperty("Id")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)categoryColumnBase0, inventoryItem.FindProperty("Category")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)costPerUnitColumnBase0, inventoryItem.FindProperty("CostPerUnit")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdDateColumnBase2, inventoryItem.FindProperty("CreatedDate")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)deletedDateColumnBase0, inventoryItem.FindProperty("DeletedDate")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)imagePathColumnBase, inventoryItem.FindProperty("ImagePath")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isDeletedColumnBase0, inventoryItem.FindProperty("IsDeleted")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastModifiedDateColumnBase0, inventoryItem.FindProperty("LastModifiedDate")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastSyncedAtColumnBase, inventoryItem.FindProperty("LastSyncedAt")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)minimumStockLevelColumnBase, inventoryItem.FindProperty("MinimumStockLevel")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, inventoryItem.FindProperty("Name")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)notesColumnBase1, inventoryItem.FindProperty("Notes")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityOnHandColumnBase, inventoryItem.FindProperty("QuantityOnHand")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)salePriceColumnBase, inventoryItem.FindProperty("SalePrice")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shopifyProductIdColumnBase, inventoryItem.FindProperty("ShopifyProductId")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shopifyVariantIdColumnBase, inventoryItem.FindProperty("ShopifyVariantId")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)skuColumnBase, inventoryItem.FindProperty("Sku")!, stockAndFlowModelsInventoryItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)supplierColumnBase, inventoryItem.FindProperty("Supplier")!, stockAndFlowModelsInventoryItemMappingBase);

            var tableMappings3 = new List<TableMapping>();
            inventoryItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var inventoryItemsTable = new Table("InventoryItems", null, relationalModel);
            var idColumn3 = new Column("Id", "TEXT", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("Id", idColumn3);
            var categoryColumn0 = new Column("Category", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("Category", categoryColumn0);
            var costPerUnitColumn0 = new Column("CostPerUnit", "decimal(18,2)", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("CostPerUnit", costPerUnitColumn0);
            var createdDateColumn2 = new Column("CreatedDate", "TEXT", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("CreatedDate", createdDateColumn2);
            var deletedDateColumn0 = new Column("DeletedDate", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("DeletedDate", deletedDateColumn0);
            var imagePathColumn = new Column("ImagePath", "TEXT", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("ImagePath", imagePathColumn);
            var isDeletedColumn0 = new Column("IsDeleted", "INTEGER", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("IsDeleted", isDeletedColumn0);
            var lastModifiedDateColumn0 = new Column("LastModifiedDate", "TEXT", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("LastModifiedDate", lastModifiedDateColumn0);
            var lastSyncedAtColumn = new Column("LastSyncedAt", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("LastSyncedAt", lastSyncedAtColumn);
            var minimumStockLevelColumn = new Column("MinimumStockLevel", "INTEGER", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("MinimumStockLevel", minimumStockLevelColumn);
            var nameColumn0 = new Column("Name", "TEXT", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("Name", nameColumn0);
            var notesColumn1 = new Column("Notes", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("Notes", notesColumn1);
            var quantityOnHandColumn = new Column("QuantityOnHand", "INTEGER", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("QuantityOnHand", quantityOnHandColumn);
            var salePriceColumn = new Column("SalePrice", "decimal(18,2)", inventoryItemsTable);
            inventoryItemsTable.Columns.Add("SalePrice", salePriceColumn);
            var shopifyProductIdColumn = new Column("ShopifyProductId", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("ShopifyProductId", shopifyProductIdColumn);
            var shopifyVariantIdColumn = new Column("ShopifyVariantId", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("ShopifyVariantId", shopifyVariantIdColumn);
            var skuColumn = new Column("Sku", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("Sku", skuColumn);
            var supplierColumn = new Column("Supplier", "TEXT", inventoryItemsTable)
            {
                IsNullable = true
            };
            inventoryItemsTable.Columns.Add("Supplier", supplierColumn);
            var pK_InventoryItems = new UniqueConstraint("PK_InventoryItems", inventoryItemsTable, new[] { idColumn3 });
            inventoryItemsTable.PrimaryKey = pK_InventoryItems;
            var pK_InventoryItemsUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "Id" });
            pK_InventoryItems.MappedKeys.Add(pK_InventoryItemsUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_InventoryItemsUc).Add(pK_InventoryItems);
            inventoryItemsTable.UniqueConstraints.Add("PK_InventoryItems", pK_InventoryItems);
            var iX_InventoryItems_Category = new TableIndex(
            "IX_InventoryItems_Category", inventoryItemsTable, new[] { categoryColumn0 }, false);
            var iX_InventoryItems_CategoryIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "Category" });
            iX_InventoryItems_Category.MappedIndexes.Add(iX_InventoryItems_CategoryIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryItems_CategoryIx).Add(iX_InventoryItems_Category);
            inventoryItemsTable.Indexes.Add("IX_InventoryItems_Category", iX_InventoryItems_Category);
            var iX_InventoryItems_IsDeleted = new TableIndex(
            "IX_InventoryItems_IsDeleted", inventoryItemsTable, new[] { isDeletedColumn0 }, false);
            var iX_InventoryItems_IsDeletedIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "IsDeleted" });
            iX_InventoryItems_IsDeleted.MappedIndexes.Add(iX_InventoryItems_IsDeletedIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryItems_IsDeletedIx).Add(iX_InventoryItems_IsDeleted);
            inventoryItemsTable.Indexes.Add("IX_InventoryItems_IsDeleted", iX_InventoryItems_IsDeleted);
            var iX_InventoryItems_Name = new TableIndex(
            "IX_InventoryItems_Name", inventoryItemsTable, new[] { nameColumn0 }, false);
            var iX_InventoryItems_NameIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "Name" });
            iX_InventoryItems_Name.MappedIndexes.Add(iX_InventoryItems_NameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryItems_NameIx).Add(iX_InventoryItems_Name);
            inventoryItemsTable.Indexes.Add("IX_InventoryItems_Name", iX_InventoryItems_Name);
            var iX_InventoryItems_ShopifyProductId = new TableIndex(
            "IX_InventoryItems_ShopifyProductId", inventoryItemsTable, new[] { shopifyProductIdColumn }, false);
            var iX_InventoryItems_ShopifyProductIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "ShopifyProductId" });
            iX_InventoryItems_ShopifyProductId.MappedIndexes.Add(iX_InventoryItems_ShopifyProductIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryItems_ShopifyProductIdIx).Add(iX_InventoryItems_ShopifyProductId);
            inventoryItemsTable.Indexes.Add("IX_InventoryItems_ShopifyProductId", iX_InventoryItems_ShopifyProductId);
            var iX_InventoryItems_Sku = new TableIndex(
            "IX_InventoryItems_Sku", inventoryItemsTable, new[] { skuColumn }, false);
            var iX_InventoryItems_SkuIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.InventoryItem",
                new[] { "Sku" });
            iX_InventoryItems_Sku.MappedIndexes.Add(iX_InventoryItems_SkuIx);
            RelationalModel.GetOrCreateTableIndexes(iX_InventoryItems_SkuIx).Add(iX_InventoryItems_Sku);
            inventoryItemsTable.Indexes.Add("IX_InventoryItems_Sku", iX_InventoryItems_Sku);
            relationalModel.Tables.Add(("InventoryItems", null), inventoryItemsTable);
            var inventoryItemsTableMapping = new TableMapping(inventoryItem, inventoryItemsTable, true);
            inventoryItemsTable.AddTypeMapping(inventoryItemsTableMapping, false);
            tableMappings3.Add(inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn3, inventoryItem.FindProperty("Id")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(categoryColumn0, inventoryItem.FindProperty("Category")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(costPerUnitColumn0, inventoryItem.FindProperty("CostPerUnit")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(createdDateColumn2, inventoryItem.FindProperty("CreatedDate")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(deletedDateColumn0, inventoryItem.FindProperty("DeletedDate")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(imagePathColumn, inventoryItem.FindProperty("ImagePath")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(isDeletedColumn0, inventoryItem.FindProperty("IsDeleted")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(lastModifiedDateColumn0, inventoryItem.FindProperty("LastModifiedDate")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(lastSyncedAtColumn, inventoryItem.FindProperty("LastSyncedAt")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(minimumStockLevelColumn, inventoryItem.FindProperty("MinimumStockLevel")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, inventoryItem.FindProperty("Name")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(notesColumn1, inventoryItem.FindProperty("Notes")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(quantityOnHandColumn, inventoryItem.FindProperty("QuantityOnHand")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(salePriceColumn, inventoryItem.FindProperty("SalePrice")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(shopifyProductIdColumn, inventoryItem.FindProperty("ShopifyProductId")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(shopifyVariantIdColumn, inventoryItem.FindProperty("ShopifyVariantId")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(skuColumn, inventoryItem.FindProperty("Sku")!, inventoryItemsTableMapping);
            RelationalModel.CreateColumnMapping(supplierColumn, inventoryItem.FindProperty("Supplier")!, inventoryItemsTableMapping);

            var sale = FindEntityType("StockAndFlow.Models.Sale")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            sale.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var stockAndFlowModelsSaleTableBase = new TableBase("StockAndFlow.Models.Sale", null, relationalModel);
            var costPerUnitColumnBase1 = new ColumnBase<ColumnMappingBase>("CostPerUnit", "decimal(18,2)", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("CostPerUnit", costPerUnitColumnBase1);
            var customerEmailColumnBase = new ColumnBase<ColumnMappingBase>("CustomerEmail", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("CustomerEmail", customerEmailColumnBase);
            var customerIdColumnBase = new ColumnBase<ColumnMappingBase>("CustomerId", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("CustomerId", customerIdColumnBase);
            var customerNameColumnBase = new ColumnBase<ColumnMappingBase>("CustomerName", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("CustomerName", customerNameColumnBase);
            var idColumnBase4 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("Id", idColumnBase4);
            var inventoryItemIdColumnBase1 = new ColumnBase<ColumnMappingBase>("InventoryItemId", "TEXT", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("InventoryItemId", inventoryItemIdColumnBase1);
            var itemNameColumnBase = new ColumnBase<ColumnMappingBase>("ItemName", "TEXT", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("ItemName", itemNameColumnBase);
            var notesColumnBase2 = new ColumnBase<ColumnMappingBase>("Notes", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("Notes", notesColumnBase2);
            var quantityColumnBase = new ColumnBase<ColumnMappingBase>("Quantity", "INTEGER", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("Quantity", quantityColumnBase);
            var saleDateColumnBase = new ColumnBase<ColumnMappingBase>("SaleDate", "TEXT", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("SaleDate", saleDateColumnBase);
            var salePricePerUnitColumnBase0 = new ColumnBase<ColumnMappingBase>("SalePricePerUnit", "decimal(18,2)", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("SalePricePerUnit", salePricePerUnitColumnBase0);
            var shopifyOrderIdColumnBase = new ColumnBase<ColumnMappingBase>("ShopifyOrderId", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("ShopifyOrderId", shopifyOrderIdColumnBase);
            var shopifyOrderNumberColumnBase = new ColumnBase<ColumnMappingBase>("ShopifyOrderNumber", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("ShopifyOrderNumber", shopifyOrderNumberColumnBase);
            var taxAmountColumnBase = new ColumnBase<ColumnMappingBase>("TaxAmount", "decimal(18,2)", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("TaxAmount", taxAmountColumnBase);
            var taxRateColumnBase = new ColumnBase<ColumnMappingBase>("TaxRate", "decimal(5,2)", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("TaxRate", taxRateColumnBase);
            var taxStateCodeColumnBase = new ColumnBase<ColumnMappingBase>("TaxStateCode", "TEXT", stockAndFlowModelsSaleTableBase)
            {
                IsNullable = true
            };
            stockAndFlowModelsSaleTableBase.Columns.Add("TaxStateCode", taxStateCodeColumnBase);
            var transactionIdColumnBase = new ColumnBase<ColumnMappingBase>("TransactionId", "TEXT", stockAndFlowModelsSaleTableBase);
            stockAndFlowModelsSaleTableBase.Columns.Add("TransactionId", transactionIdColumnBase);
            relationalModel.DefaultTables.Add("StockAndFlow.Models.Sale", stockAndFlowModelsSaleTableBase);
            var stockAndFlowModelsSaleMappingBase = new TableMappingBase<ColumnMappingBase>(sale, stockAndFlowModelsSaleTableBase, true);
            stockAndFlowModelsSaleTableBase.AddTypeMapping(stockAndFlowModelsSaleMappingBase, false);
            defaultTableMappings4.Add(stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase4, sale.FindProperty("Id")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)costPerUnitColumnBase1, sale.FindProperty("CostPerUnit")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customerEmailColumnBase, sale.FindProperty("CustomerEmail")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customerIdColumnBase, sale.FindProperty("CustomerId")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)customerNameColumnBase, sale.FindProperty("CustomerName")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)inventoryItemIdColumnBase1, sale.FindProperty("InventoryItemId")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)itemNameColumnBase, sale.FindProperty("ItemName")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)notesColumnBase2, sale.FindProperty("Notes")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)quantityColumnBase, sale.FindProperty("Quantity")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)saleDateColumnBase, sale.FindProperty("SaleDate")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)salePricePerUnitColumnBase0, sale.FindProperty("SalePricePerUnit")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shopifyOrderIdColumnBase, sale.FindProperty("ShopifyOrderId")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shopifyOrderNumberColumnBase, sale.FindProperty("ShopifyOrderNumber")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)taxAmountColumnBase, sale.FindProperty("TaxAmount")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)taxRateColumnBase, sale.FindProperty("TaxRate")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)taxStateCodeColumnBase, sale.FindProperty("TaxStateCode")!, stockAndFlowModelsSaleMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)transactionIdColumnBase, sale.FindProperty("TransactionId")!, stockAndFlowModelsSaleMappingBase);

            var tableMappings4 = new List<TableMapping>();
            sale.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var salesTable = new Table("Sales", null, relationalModel);
            var idColumn4 = new Column("Id", "TEXT", salesTable);
            salesTable.Columns.Add("Id", idColumn4);
            var costPerUnitColumn1 = new Column("CostPerUnit", "decimal(18,2)", salesTable);
            salesTable.Columns.Add("CostPerUnit", costPerUnitColumn1);
            var customerEmailColumn = new Column("CustomerEmail", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("CustomerEmail", customerEmailColumn);
            var customerIdColumn = new Column("CustomerId", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("CustomerId", customerIdColumn);
            var customerNameColumn = new Column("CustomerName", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("CustomerName", customerNameColumn);
            var inventoryItemIdColumn1 = new Column("InventoryItemId", "TEXT", salesTable);
            salesTable.Columns.Add("InventoryItemId", inventoryItemIdColumn1);
            var itemNameColumn = new Column("ItemName", "TEXT", salesTable);
            salesTable.Columns.Add("ItemName", itemNameColumn);
            var notesColumn2 = new Column("Notes", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("Notes", notesColumn2);
            var quantityColumn = new Column("Quantity", "INTEGER", salesTable);
            salesTable.Columns.Add("Quantity", quantityColumn);
            var saleDateColumn = new Column("SaleDate", "TEXT", salesTable);
            salesTable.Columns.Add("SaleDate", saleDateColumn);
            var salePricePerUnitColumn0 = new Column("SalePricePerUnit", "decimal(18,2)", salesTable);
            salesTable.Columns.Add("SalePricePerUnit", salePricePerUnitColumn0);
            var shopifyOrderIdColumn = new Column("ShopifyOrderId", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("ShopifyOrderId", shopifyOrderIdColumn);
            var shopifyOrderNumberColumn = new Column("ShopifyOrderNumber", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("ShopifyOrderNumber", shopifyOrderNumberColumn);
            var taxAmountColumn = new Column("TaxAmount", "decimal(18,2)", salesTable);
            salesTable.Columns.Add("TaxAmount", taxAmountColumn);
            var taxRateColumn = new Column("TaxRate", "decimal(5,2)", salesTable);
            salesTable.Columns.Add("TaxRate", taxRateColumn);
            var taxStateCodeColumn = new Column("TaxStateCode", "TEXT", salesTable)
            {
                IsNullable = true
            };
            salesTable.Columns.Add("TaxStateCode", taxStateCodeColumn);
            var transactionIdColumn = new Column("TransactionId", "TEXT", salesTable);
            salesTable.Columns.Add("TransactionId", transactionIdColumn);
            var pK_Sales = new UniqueConstraint("PK_Sales", salesTable, new[] { idColumn4 });
            salesTable.PrimaryKey = pK_Sales;
            var pK_SalesUc = RelationalModel.GetKey(this,
                "StockAndFlow.Models.Sale",
                new[] { "Id" });
            pK_Sales.MappedKeys.Add(pK_SalesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SalesUc).Add(pK_Sales);
            salesTable.UniqueConstraints.Add("PK_Sales", pK_Sales);
            var iX_Sales_CustomerId = new TableIndex(
            "IX_Sales_CustomerId", salesTable, new[] { customerIdColumn }, false);
            var iX_Sales_CustomerIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "CustomerId" });
            iX_Sales_CustomerId.MappedIndexes.Add(iX_Sales_CustomerIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_CustomerIdIx).Add(iX_Sales_CustomerId);
            salesTable.Indexes.Add("IX_Sales_CustomerId", iX_Sales_CustomerId);
            var iX_Sales_InventoryItemId = new TableIndex(
            "IX_Sales_InventoryItemId", salesTable, new[] { inventoryItemIdColumn1 }, false);
            var iX_Sales_InventoryItemIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "InventoryItemId" });
            iX_Sales_InventoryItemId.MappedIndexes.Add(iX_Sales_InventoryItemIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_InventoryItemIdIx).Add(iX_Sales_InventoryItemId);
            salesTable.Indexes.Add("IX_Sales_InventoryItemId", iX_Sales_InventoryItemId);
            var iX_Sales_InventoryItemId_SaleDate = new TableIndex(
            "IX_Sales_InventoryItemId_SaleDate", salesTable, new[] { inventoryItemIdColumn1, saleDateColumn }, false);
            var iX_Sales_InventoryItemId_SaleDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "InventoryItemId", "SaleDate" });
            iX_Sales_InventoryItemId_SaleDate.MappedIndexes.Add(iX_Sales_InventoryItemId_SaleDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_InventoryItemId_SaleDateIx).Add(iX_Sales_InventoryItemId_SaleDate);
            salesTable.Indexes.Add("IX_Sales_InventoryItemId_SaleDate", iX_Sales_InventoryItemId_SaleDate);
            var iX_Sales_SaleDate = new TableIndex(
            "IX_Sales_SaleDate", salesTable, new[] { saleDateColumn }, false);
            var iX_Sales_SaleDateIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "SaleDate" });
            iX_Sales_SaleDate.MappedIndexes.Add(iX_Sales_SaleDateIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_SaleDateIx).Add(iX_Sales_SaleDate);
            salesTable.Indexes.Add("IX_Sales_SaleDate", iX_Sales_SaleDate);
            var iX_Sales_ShopifyOrderId = new TableIndex(
            "IX_Sales_ShopifyOrderId", salesTable, new[] { shopifyOrderIdColumn }, false);
            var iX_Sales_ShopifyOrderIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "ShopifyOrderId" });
            iX_Sales_ShopifyOrderId.MappedIndexes.Add(iX_Sales_ShopifyOrderIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_ShopifyOrderIdIx).Add(iX_Sales_ShopifyOrderId);
            salesTable.Indexes.Add("IX_Sales_ShopifyOrderId", iX_Sales_ShopifyOrderId);
            var iX_Sales_TransactionId = new TableIndex(
            "IX_Sales_TransactionId", salesTable, new[] { transactionIdColumn }, false);
            var iX_Sales_TransactionIdIx = RelationalModel.GetIndex(this,
                "StockAndFlow.Models.Sale",
                new[] { "TransactionId" });
            iX_Sales_TransactionId.MappedIndexes.Add(iX_Sales_TransactionIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Sales_TransactionIdIx).Add(iX_Sales_TransactionId);
            salesTable.Indexes.Add("IX_Sales_TransactionId", iX_Sales_TransactionId);
            relationalModel.Tables.Add(("Sales", null), salesTable);
            var salesTableMapping = new TableMapping(sale, salesTable, true);
            salesTable.AddTypeMapping(salesTableMapping, false);
            tableMappings4.Add(salesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn4, sale.FindProperty("Id")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(costPerUnitColumn1, sale.FindProperty("CostPerUnit")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(customerEmailColumn, sale.FindProperty("CustomerEmail")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(customerIdColumn, sale.FindProperty("CustomerId")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(customerNameColumn, sale.FindProperty("CustomerName")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(inventoryItemIdColumn1, sale.FindProperty("InventoryItemId")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(itemNameColumn, sale.FindProperty("ItemName")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(notesColumn2, sale.FindProperty("Notes")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(quantityColumn, sale.FindProperty("Quantity")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(saleDateColumn, sale.FindProperty("SaleDate")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(salePricePerUnitColumn0, sale.FindProperty("SalePricePerUnit")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(shopifyOrderIdColumn, sale.FindProperty("ShopifyOrderId")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(shopifyOrderNumberColumn, sale.FindProperty("ShopifyOrderNumber")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(taxAmountColumn, sale.FindProperty("TaxAmount")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(taxRateColumn, sale.FindProperty("TaxRate")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(taxStateCodeColumn, sale.FindProperty("TaxStateCode")!, salesTableMapping);
            RelationalModel.CreateColumnMapping(transactionIdColumn, sale.FindProperty("TransactionId")!, salesTableMapping);
            var fK_Expenses_InventoryItems_InventoryItemId = new ForeignKeyConstraint(
                "FK_Expenses_InventoryItems_InventoryItemId", expensesTable, inventoryItemsTable,
                new[] { inventoryItemIdColumn },
                inventoryItemsTable.FindUniqueConstraint("PK_InventoryItems")!, ReferentialAction.SetNull);
            var fK_Expenses_InventoryItems_InventoryItemIdFk = RelationalModel.GetForeignKey(this,
                "StockAndFlow.Models.Expense",
                new[] { "InventoryItemId" },
                "StockAndFlow.Models.InventoryItem",
                new[] { "Id" });
            fK_Expenses_InventoryItems_InventoryItemId.MappedForeignKeys.Add(fK_Expenses_InventoryItems_InventoryItemIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Expenses_InventoryItems_InventoryItemIdFk).Add(fK_Expenses_InventoryItems_InventoryItemId);
            expensesTable.ForeignKeyConstraints.Add(fK_Expenses_InventoryItems_InventoryItemId);
            inventoryItemsTable.ReferencingForeignKeyConstraints.Add(fK_Expenses_InventoryItems_InventoryItemId);
            var fK_InventoryAdjustments_InventoryItems_InventoryItemId = new ForeignKeyConstraint(
                "FK_InventoryAdjustments_InventoryItems_InventoryItemId", inventoryAdjustmentsTable, inventoryItemsTable,
                new[] { inventoryItemIdColumn0 },
                inventoryItemsTable.FindUniqueConstraint("PK_InventoryItems")!, ReferentialAction.Restrict);
            var fK_InventoryAdjustments_InventoryItems_InventoryItemIdFk = RelationalModel.GetForeignKey(this,
                "StockAndFlow.Models.InventoryAdjustment",
                new[] { "InventoryItemId" },
                "StockAndFlow.Models.InventoryItem",
                new[] { "Id" });
            fK_InventoryAdjustments_InventoryItems_InventoryItemId.MappedForeignKeys.Add(fK_InventoryAdjustments_InventoryItems_InventoryItemIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_InventoryAdjustments_InventoryItems_InventoryItemIdFk).Add(fK_InventoryAdjustments_InventoryItems_InventoryItemId);
            inventoryAdjustmentsTable.ForeignKeyConstraints.Add(fK_InventoryAdjustments_InventoryItems_InventoryItemId);
            inventoryItemsTable.ReferencingForeignKeyConstraints.Add(fK_InventoryAdjustments_InventoryItems_InventoryItemId);
            var fK_Sales_Customers_CustomerId = new ForeignKeyConstraint(
                "FK_Sales_Customers_CustomerId", salesTable, customersTable,
                new[] { customerIdColumn },
                customersTable.FindUniqueConstraint("PK_Customers")!, ReferentialAction.SetNull);
            var fK_Sales_Customers_CustomerIdFk = RelationalModel.GetForeignKey(this,
                "StockAndFlow.Models.Sale",
                new[] { "CustomerId" },
                "StockAndFlow.Models.Customer",
                new[] { "Id" });
            fK_Sales_Customers_CustomerId.MappedForeignKeys.Add(fK_Sales_Customers_CustomerIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Sales_Customers_CustomerIdFk).Add(fK_Sales_Customers_CustomerId);
            salesTable.ForeignKeyConstraints.Add(fK_Sales_Customers_CustomerId);
            customersTable.ReferencingForeignKeyConstraints.Add(fK_Sales_Customers_CustomerId);
            var fK_Sales_InventoryItems_InventoryItemId = new ForeignKeyConstraint(
                "FK_Sales_InventoryItems_InventoryItemId", salesTable, inventoryItemsTable,
                new[] { inventoryItemIdColumn1 },
                inventoryItemsTable.FindUniqueConstraint("PK_InventoryItems")!, ReferentialAction.Restrict);
            var fK_Sales_InventoryItems_InventoryItemIdFk = RelationalModel.GetForeignKey(this,
                "StockAndFlow.Models.Sale",
                new[] { "InventoryItemId" },
                "StockAndFlow.Models.InventoryItem",
                new[] { "Id" });
            fK_Sales_InventoryItems_InventoryItemId.MappedForeignKeys.Add(fK_Sales_InventoryItems_InventoryItemIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Sales_InventoryItems_InventoryItemIdFk).Add(fK_Sales_InventoryItems_InventoryItemId);
            salesTable.ForeignKeyConstraints.Add(fK_Sales_InventoryItems_InventoryItemId);
            inventoryItemsTable.ReferencingForeignKeyConstraints.Add(fK_Sales_InventoryItems_InventoryItemId);
            return relationalModel.MakeReadOnly();
        }
    }
}
